// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.11.4
// source: EventService.proto

package internalising

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventServiceClient interface {
	Create(ctx context.Context, in *Event, opts ...grpc.CallOption) (*ResponseEvent, error)
	Update(ctx context.Context, in *Event, opts ...grpc.CallOption) (*ResponseEvent, error)
	Delete(ctx context.Context, in *DeleteEvent, opts ...grpc.CallOption) (*ResponseEvent, error)
	FindAll(ctx context.Context, in *RequestEventList, opts ...grpc.CallOption) (*ResponseEventList, error)
	EventsListDay(ctx context.Context, in *RequestEventList, opts ...grpc.CallOption) (*ResponseEventList, error)
	EventsListWeek(ctx context.Context, in *RequestEventList, opts ...grpc.CallOption) (*ResponseEventList, error)
	EventsListMonth(ctx context.Context, in *RequestEventList, opts ...grpc.CallOption) (*ResponseEventList, error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) Create(ctx context.Context, in *Event, opts ...grpc.CallOption) (*ResponseEvent, error) {
	out := new(ResponseEvent)
	err := c.cc.Invoke(ctx, "/event.EventService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) Update(ctx context.Context, in *Event, opts ...grpc.CallOption) (*ResponseEvent, error) {
	out := new(ResponseEvent)
	err := c.cc.Invoke(ctx, "/event.EventService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) Delete(ctx context.Context, in *DeleteEvent, opts ...grpc.CallOption) (*ResponseEvent, error) {
	out := new(ResponseEvent)
	err := c.cc.Invoke(ctx, "/event.EventService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) FindAll(ctx context.Context, in *RequestEventList, opts ...grpc.CallOption) (*ResponseEventList, error) {
	out := new(ResponseEventList)
	err := c.cc.Invoke(ctx, "/event.EventService/FindAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) EventsListDay(ctx context.Context, in *RequestEventList, opts ...grpc.CallOption) (*ResponseEventList, error) {
	out := new(ResponseEventList)
	err := c.cc.Invoke(ctx, "/event.EventService/EventsListDay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) EventsListWeek(ctx context.Context, in *RequestEventList, opts ...grpc.CallOption) (*ResponseEventList, error) {
	out := new(ResponseEventList)
	err := c.cc.Invoke(ctx, "/event.EventService/EventsListWeek", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) EventsListMonth(ctx context.Context, in *RequestEventList, opts ...grpc.CallOption) (*ResponseEventList, error) {
	out := new(ResponseEventList)
	err := c.cc.Invoke(ctx, "/event.EventService/EventsListMonth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
// All implementations must embed UnimplementedEventServiceServer
// for forward compatibility
type EventServiceServer interface {
	Create(context.Context, *Event) (*ResponseEvent, error)
	Update(context.Context, *Event) (*ResponseEvent, error)
	Delete(context.Context, *DeleteEvent) (*ResponseEvent, error)
	FindAll(context.Context, *RequestEventList) (*ResponseEventList, error)
	EventsListDay(context.Context, *RequestEventList) (*ResponseEventList, error)
	EventsListWeek(context.Context, *RequestEventList) (*ResponseEventList, error)
	EventsListMonth(context.Context, *RequestEventList) (*ResponseEventList, error)
	mustEmbedUnimplementedEventServiceServer()
}

// UnimplementedEventServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEventServiceServer struct {
}

func (UnimplementedEventServiceServer) Create(context.Context, *Event) (*ResponseEvent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedEventServiceServer) Update(context.Context, *Event) (*ResponseEvent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedEventServiceServer) Delete(context.Context, *DeleteEvent) (*ResponseEvent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedEventServiceServer) FindAll(context.Context, *RequestEventList) (*ResponseEventList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedEventServiceServer) EventsListDay(context.Context, *RequestEventList) (*ResponseEventList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EventsListDay not implemented")
}
func (UnimplementedEventServiceServer) EventsListWeek(context.Context, *RequestEventList) (*ResponseEventList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EventsListWeek not implemented")
}
func (UnimplementedEventServiceServer) EventsListMonth(context.Context, *RequestEventList) (*ResponseEventList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EventsListMonth not implemented")
}
func (UnimplementedEventServiceServer) mustEmbedUnimplementedEventServiceServer() {}

// UnsafeEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceServer will
// result in compilation errors.
type UnsafeEventServiceServer interface {
	mustEmbedUnimplementedEventServiceServer()
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	s.RegisterService(&EventService_ServiceDesc, srv)
}

func _EventService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Create(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Update(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Delete(ctx, req.(*DeleteEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEventList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/FindAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).FindAll(ctx, req.(*RequestEventList))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_EventsListDay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEventList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).EventsListDay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/EventsListDay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).EventsListDay(ctx, req.(*RequestEventList))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_EventsListWeek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEventList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).EventsListWeek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/EventsListWeek",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).EventsListWeek(ctx, req.(*RequestEventList))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_EventsListMonth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEventList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).EventsListMonth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/EventsListMonth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).EventsListMonth(ctx, req.(*RequestEventList))
	}
	return interceptor(ctx, in, info, handler)
}

// EventService_ServiceDesc is the grpc.ServiceDesc for EventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "event.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _EventService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _EventService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _EventService_Delete_Handler,
		},
		{
			MethodName: "FindAll",
			Handler:    _EventService_FindAll_Handler,
		},
		{
			MethodName: "EventsListDay",
			Handler:    _EventService_EventsListDay_Handler,
		},
		{
			MethodName: "EventsListWeek",
			Handler:    _EventService_EventsListWeek_Handler,
		},
		{
			MethodName: "EventsListMonth",
			Handler:    _EventService_EventsListMonth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "EventService.proto",
}
